{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 0, "revision": 0, "architecture": "x64"},
    "classnamespace": "box",
    "rect": [80.0, 80.0, 760.0, 520.0],
    "boxes": [
      {"box":{"id":"in-l","maxclass":"newobj","text":"inlet","patching_rect":[30.0,30.0,40.0,22.0]}},
      {"box":{"id":"in-r","maxclass":"newobj","text":"inlet","patching_rect":[110.0,30.0,40.0,22.0]}},
      {"box":{"id":"shift","maxclass":"newobj","text":"inlet","patching_rect":[210.0,30.0,35.0,22.0]}},
      {"box":{"id":"direction","maxclass":"newobj","text":"inlet","patching_rect":[290.0,30.0,35.0,22.0]}},
      {"box":{"id":"clip","maxclass":"newobj","text":"clip -5000. 5000.","patching_rect":[210.0,70.0,120.0,22.0]}},
      {"box":{"id":"pack","maxclass":"newobj","text":"pack 0. 20","patching_rect":[210.0,105.0,75.0,22.0]}},
      {"box":{"id":"line","maxclass":"newobj","text":"line~","patching_rect":[210.0,140.0,42.0,22.0]}},
      {"box":{"id":"dir-l","maxclass":"newobj","text":"expr 1.-2.*($i1==1)","patching_rect":[290.0,70.0,130.0,22.0]}},
      {"box":{"id":"dir-r","maxclass":"newobj","text":"expr 1.-2.*($i1==1 || $i1==2)","patching_rect":[450.0,70.0,195.0,22.0]}},
      {"box":{"id":"sig-l","maxclass":"newobj","text":"sig~ 1.","patching_rect":[310.0,140.0,48.0,22.0]}},
      {"box":{"id":"sig-r","maxclass":"newobj","text":"sig~ 1.","patching_rect":[470.0,140.0,48.0,22.0]}},
      {"box":{"id":"mul-f-l","maxclass":"newobj","text":"*~","patching_rect":[210.0,180.0,35.0,22.0]}},
      {"box":{"id":"mul-f-r","maxclass":"newobj","text":"*~","patching_rect":[370.0,180.0,35.0,22.0]}},
      {"box":{"id":"osc-l","maxclass":"newobj","text":"phasor~","patching_rect":[210.0,220.0,52.0,22.0]}},
      {"box":{"id":"osc-r","maxclass":"newobj","text":"phasor~","patching_rect":[370.0,220.0,52.0,22.0]}},
      {"box":{"id":"phase-l","maxclass":"newobj","text":"+~ 0.25","patching_rect":[275.0,220.0,58.0,22.0]}},
      {"box":{"id":"phase-r","maxclass":"newobj","text":"+~ 0.25","patching_rect":[435.0,220.0,58.0,22.0]}},
      {"box":{"id":"cos-l","maxclass":"newobj","text":"cos~","patching_rect":[210.0,250.0,42.0,22.0]}},
      {"box":{"id":"sin-l","maxclass":"newobj","text":"cos~","patching_rect":[275.0,250.0,42.0,22.0]}},
      {"box":{"id":"cos-r","maxclass":"newobj","text":"cos~","patching_rect":[370.0,250.0,42.0,22.0]}},
      {"box":{"id":"sin-r","maxclass":"newobj","text":"cos~","patching_rect":[435.0,250.0,42.0,22.0]}},
      {"box":{"id":"hilb-l","maxclass":"newobj","text":"hilbert~","patching_rect":[30.0,180.0,55.0,22.0]}},
      {"box":{"id":"hilb-r","maxclass":"newobj","text":"hilbert~","patching_rect":[110.0,180.0,55.0,22.0]}},
      {"box":{"id":"l-real","maxclass":"newobj","text":"*~","patching_rect":[30.0,275.0,35.0,22.0]}},
      {"box":{"id":"l-imag","maxclass":"newobj","text":"*~","patching_rect":[80.0,275.0,35.0,22.0]}},
      {"box":{"id":"l-sub","maxclass":"newobj","text":"-~","patching_rect":[55.0,320.0,35.0,22.0]}},
      {"box":{"id":"r-real","maxclass":"newobj","text":"*~","patching_rect":[150.0,275.0,35.0,22.0]}},
      {"box":{"id":"r-imag","maxclass":"newobj","text":"*~","patching_rect":[200.0,275.0,35.0,22.0]}},
      {"box":{"id":"r-sub","maxclass":"newobj","text":"-~","patching_rect":[175.0,320.0,35.0,22.0]}},
      {"box":{"id":"out-l","maxclass":"newobj","text":"outlet","patching_rect":[55.0,380.0,45.0,22.0]}},
      {"box":{"id":"out-r","maxclass":"newobj","text":"outlet","patching_rect":[175.0,380.0,45.0,22.0]}}
    ],
    "lines": [
      {"patchline":{"source":["in-l",0],"destination":["hilb-l",0]}},
      {"patchline":{"source":["in-r",0],"destination":["hilb-r",0]}},
      {"patchline":{"source":["shift",0],"destination":["clip",0]}},
      {"patchline":{"source":["clip",0],"destination":["pack",0]}},
      {"patchline":{"source":["pack",0],"destination":["line",0]}},
      {"patchline":{"source":["direction",0],"destination":["dir-l",0]}},
      {"patchline":{"source":["direction",0],"destination":["dir-r",0]}},
      {"patchline":{"source":["dir-l",0],"destination":["sig-l",0]}},
      {"patchline":{"source":["dir-r",0],"destination":["sig-r",0]}},
      {"patchline":{"source":["line",0],"destination":["mul-f-l",0]}},
      {"patchline":{"source":["sig-l",0],"destination":["mul-f-l",1]}},
      {"patchline":{"source":["line",0],"destination":["mul-f-r",0]}},
      {"patchline":{"source":["sig-r",0],"destination":["mul-f-r",1]}},
      {"patchline":{"source":["mul-f-l",0],"destination":["osc-l",0]}},
      {"patchline":{"source":["mul-f-r",0],"destination":["osc-r",0]}},
      {"patchline":{"source":["osc-l",0],"destination":["phase-l",0]}},
      {"patchline":{"source":["osc-r",0],"destination":["phase-r",0]}},
      {"patchline":{"source":["osc-l",0],"destination":["cos-l",0]}},
      {"patchline":{"source":["phase-l",0],"destination":["sin-l",0]}},
      {"patchline":{"source":["osc-r",0],"destination":["cos-r",0]}},
      {"patchline":{"source":["phase-r",0],"destination":["sin-r",0]}},
      {"patchline":{"source":["hilb-l",0],"destination":["l-real",0]}},
      {"patchline":{"source":["cos-l",0],"destination":["l-real",1]}},
      {"patchline":{"source":["hilb-l",1],"destination":["l-imag",0]}},
      {"patchline":{"source":["sin-l",0],"destination":["l-imag",1]}},
      {"patchline":{"source":["l-real",0],"destination":["l-sub",0]}},
      {"patchline":{"source":["l-imag",0],"destination":["l-sub",1]}},
      {"patchline":{"source":["l-sub",0],"destination":["out-l",0]}},
      {"patchline":{"source":["hilb-r",0],"destination":["r-real",0]}},
      {"patchline":{"source":["cos-r",0],"destination":["r-real",1]}},
      {"patchline":{"source":["hilb-r",1],"destination":["r-imag",0]}},
      {"patchline":{"source":["sin-r",0],"destination":["r-imag",1]}},
      {"patchline":{"source":["r-real",0],"destination":["r-sub",0]}},
      {"patchline":{"source":["r-imag",0],"destination":["r-sub",1]}},
      {"patchline":{"source":["r-sub",0],"destination":["out-r",0]}}
    ]
  }
}
