{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 0, "revision": 0, "architecture": "x64"},
    "classnamespace": "box",
    "rect": [80.0, 80.0, 760.0, 430.0],
    "boxes": [
      {"box":{"id":"audio","maxclass":"newobj","text":"inlet","patching_rect":[30.0,30.0,40.0,22.0]}},
      {"box":{"id":"rate","maxclass":"newobj","text":"inlet","patching_rect":[110.0,30.0,35.0,22.0]}},
      {"box":{"id":"shape","maxclass":"newobj","text":"inlet","patching_rect":[180.0,30.0,35.0,22.0]}},
      {"box":{"id":"attack","maxclass":"newobj","text":"inlet","patching_rect":[250.0,30.0,35.0,22.0]}},
      {"box":{"id":"release","maxclass":"newobj","text":"inlet","patching_rect":[320.0,30.0,35.0,22.0]}},
      {"box":{"id":"clip-rate","maxclass":"newobj","text":"clip 0.01 20.","patching_rect":[110.0,70.0,85.0,22.0]}},
      {"box":{"id":"phasor","maxclass":"newobj","text":"phasor~ 0.25","patching_rect":[110.0,115.0,75.0,22.0]}},
      {"box":{"id":"sine","maxclass":"newobj","text":"cos~","patching_rect":[110.0,155.0,42.0,22.0]}},
      {"box":{"id":"tri","maxclass":"newobj","text":"triangle~ 1.","patching_rect":[175.0,155.0,75.0,22.0]}},
      {"box":{"id":"saw","maxclass":"newobj","text":"*~ 2.","patching_rect":[270.0,155.0,42.0,22.0]}},
      {"box":{"id":"saw-offset","maxclass":"newobj","text":"-~ 1.","patching_rect":[270.0,190.0,42.0,22.0]}},
      {"box":{"id":"square-cmp","maxclass":"newobj","text":">~ 0.5","patching_rect":[335.0,155.0,50.0,22.0]}},
      {"box":{"id":"square-scale","maxclass":"newobj","text":"*~ 2.","patching_rect":[335.0,190.0,42.0,22.0]}},
      {"box":{"id":"square-offset","maxclass":"newobj","text":"-~ 1.","patching_rect":[335.0,225.0,42.0,22.0]}},
      {"box":{"id":"noise","maxclass":"newobj","text":"noise~","patching_rect":[410.0,155.0,48.0,22.0]}},
      {"box":{"id":"random-rate","maxclass":"newobj","text":"sah~","patching_rect":[410.0,190.0,42.0,22.0]}},
      {"box":{"id":"selector","maxclass":"newobj","text":"selector~ 5","patching_rect":[180.0,275.0,80.0,22.0]}},
      {"box":{"id":"shape-index","maxclass":"newobj","text":"+ 1","patching_rect":[180.0,70.0,35.0,22.0]}},
      {"box":{"id":"abs","maxclass":"newobj","text":"abs~","patching_rect":[30.0,115.0,42.0,22.0]}},
      {"box":{"id":"slide","maxclass":"newobj","text":"slide~ 10 1000","patching_rect":[30.0,155.0,95.0,22.0]}},
      {"box":{"id":"env-scale","maxclass":"newobj","text":"*~ 2.","patching_rect":[30.0,200.0,42.0,22.0]}},
      {"box":{"id":"env-offset","maxclass":"newobj","text":"-~ 1.","patching_rect":[30.0,235.0,42.0,22.0]}},
      {"box":{"id":"lfo-out","maxclass":"newobj","text":"outlet","patching_rect":[180.0,340.0,45.0,22.0]}},
      {"box":{"id":"env-out","maxclass":"newobj","text":"outlet","patching_rect":[30.0,340.0,45.0,22.0]}}
    ],
    "lines": [
      {"patchline":{"source":["audio",0],"destination":["abs",0]}},
      {"patchline":{"source":["abs",0],"destination":["slide",0]}},
      {"patchline":{"source":["attack",0],"destination":["slide",1]}},
      {"patchline":{"source":["release",0],"destination":["slide",2]}},
      {"patchline":{"source":["slide",0],"destination":["env-scale",0]}},
      {"patchline":{"source":["env-scale",0],"destination":["env-offset",0]}},
      {"patchline":{"source":["env-offset",0],"destination":["env-out",0]}},
      {"patchline":{"source":["rate",0],"destination":["clip-rate",0]}},
      {"patchline":{"source":["clip-rate",0],"destination":["phasor",0]}},
      {"patchline":{"source":["phasor",0],"destination":["sine",0]}},
      {"patchline":{"source":["phasor",0],"destination":["tri",0]}},
      {"patchline":{"source":["phasor",0],"destination":["saw",0]}},
      {"patchline":{"source":["saw",0],"destination":["saw-offset",0]}},
      {"patchline":{"source":["phasor",0],"destination":["square-cmp",0]}},
      {"patchline":{"source":["square-cmp",0],"destination":["square-scale",0]}},
      {"patchline":{"source":["square-scale",0],"destination":["square-offset",0]}},
      {"patchline":{"source":["noise",0],"destination":["random-rate",0]}},
      {"patchline":{"source":["square-cmp",0],"destination":["random-rate",1]}},
      {"patchline":{"source":["shape",0],"destination":["shape-index",0]}},
      {"patchline":{"source":["shape-index",0],"destination":["selector",0]}},
      {"patchline":{"source":["sine",0],"destination":["selector",1]}},
      {"patchline":{"source":["tri",0],"destination":["selector",2]}},
      {"patchline":{"source":["saw-offset",0],"destination":["selector",3]}},
      {"patchline":{"source":["square-offset",0],"destination":["selector",4]}},
      {"patchline":{"source":["random-rate",0],"destination":["selector",5]}},
      {"patchline":{"source":["selector",0],"destination":["lfo-out",0]}}
    ]
  }
}
