{
  "patcher": {
    "fileversion":1,
    "appversion":{"major":9,"minor":0,"revision":0,"architecture":"x64"},
    "classnamespace":"box",
    "rect":[70.0,70.0,760.0,440.0],
    "boxes":[
      {"box":{"id":"in-l","maxclass":"newobj","text":"inlet","patching_rect":[30.0,30.0,40.0,22.0]}},
      {"box":{"id":"in-r","maxclass":"newobj","text":"inlet","patching_rect":[100.0,30.0,40.0,22.0]}},
      {"box":{"id":"translate","maxclass":"newobj","text":"inlet","patching_rect":[200.0,30.0,35.0,22.0]}},
      {"box":{"id":"scale","maxclass":"newobj","text":"inlet","patching_rect":[270.0,30.0,35.0,22.0]}},
      {"box":{"id":"pivot","maxclass":"newobj","text":"inlet","patching_rect":[340.0,30.0,35.0,22.0]}},
      {"box":{"id":"quality","maxclass":"newobj","text":"inlet","patching_rect":[410.0,30.0,35.0,22.0]}},
      {"box":{"id":"clip-scale","maxclass":"newobj","text":"clip 0.25 4.","patching_rect":[270.0,70.0,80.0,22.0]}},
      {"box":{"id":"send-scale","maxclass":"newobj","text":"s vectorshift-scale","patching_rect":[270.0,105.0,115.0,22.0]}},
      {"box":{"id":"translate-pak","maxclass":"newobj","text":"pak 0. 1. 1000.","patching_rect":[340.0,105.0,105.0,22.0]}},
      {"box":{"id":"pivot-shift","maxclass":"newobj","text":"expr $f1+$f3*(1.-$f2)","patching_rect":[340.0,140.0,145.0,22.0]}},
      {"box":{"id":"pfft-l-low","maxclass":"newobj","text":"pfft~ spectral-core-low 1024 4","patching_rect":[30.0,105.0,195.0,22.0]}},
      {"box":{"id":"pfft-r-low","maxclass":"newobj","text":"pfft~ spectral-core-low 1024 4","patching_rect":[30.0,135.0,195.0,22.0]}},
      {"box":{"id":"pfft-l-normal","maxclass":"newobj","text":"pfft~ spectral-core 2048 4","patching_rect":[250.0,105.0,165.0,22.0]}},
      {"box":{"id":"pfft-r-normal","maxclass":"newobj","text":"pfft~ spectral-core 2048 4","patching_rect":[250.0,135.0,165.0,22.0]}},
      {"box":{"id":"pfft-l-high","maxclass":"newobj","text":"pfft~ spectral-core-high 4096 4","patching_rect":[440.0,105.0,200.0,22.0]}},
      {"box":{"id":"pfft-r-high","maxclass":"newobj","text":"pfft~ spectral-core-high 4096 4","patching_rect":[440.0,135.0,200.0,22.0]}},
      {"box":{"id":"quality-index","maxclass":"newobj","text":"+ 1","patching_rect":[410.0,70.0,35.0,22.0]}},
      {"box":{"id":"quality-select-l","maxclass":"newobj","text":"selector~ 3","patching_rect":[120.0,175.0,75.0,22.0]}},
      {"box":{"id":"quality-select-r","maxclass":"newobj","text":"selector~ 3","patching_rect":[220.0,175.0,75.0,22.0]}},
      {"box":{"id":"shift","maxclass":"newobj","text":"classic-engine","patching_rect":[30.0,225.0,100.0,22.0]}},
      {"box":{"id":"direction-zero","maxclass":"message","text":"0","patching_rect":[220.0,190.0,30.0,22.0]}},
      {"box":{"id":"load","maxclass":"newobj","text":"loadbang","patching_rect":[220.0,150.0,60.0,22.0]}},
      {"box":{"id":"out-l","maxclass":"newobj","text":"outlet","patching_rect":[30.0,300.0,45.0,22.0]}},
      {"box":{"id":"out-r","maxclass":"newobj","text":"outlet","patching_rect":[100.0,300.0,45.0,22.0]}}
    ],
    "lines":[
      {"patchline":{"source":["in-l",0],"destination":["pfft-l-low",0]}},{"patchline":{"source":["in-l",0],"destination":["pfft-l-normal",0]}},{"patchline":{"source":["in-l",0],"destination":["pfft-l-high",0]}},
      {"patchline":{"source":["in-r",0],"destination":["pfft-r-low",0]}},{"patchline":{"source":["in-r",0],"destination":["pfft-r-normal",0]}},{"patchline":{"source":["in-r",0],"destination":["pfft-r-high",0]}},
      {"patchline":{"source":["scale",0],"destination":["clip-scale",0]}},
      {"patchline":{"source":["clip-scale",0],"destination":["send-scale",0]}},
      {"patchline":{"source":["quality",0],"destination":["quality-index",0]}},{"patchline":{"source":["quality-index",0],"destination":["quality-select-l",0]}},{"patchline":{"source":["quality-index",0],"destination":["quality-select-r",0]}},
      {"patchline":{"source":["pfft-l-low",0],"destination":["quality-select-l",1]}},{"patchline":{"source":["pfft-l-normal",0],"destination":["quality-select-l",2]}},{"patchline":{"source":["pfft-l-high",0],"destination":["quality-select-l",3]}},
      {"patchline":{"source":["pfft-r-low",0],"destination":["quality-select-r",1]}},{"patchline":{"source":["pfft-r-normal",0],"destination":["quality-select-r",2]}},{"patchline":{"source":["pfft-r-high",0],"destination":["quality-select-r",3]}},
      {"patchline":{"source":["quality-select-l",0],"destination":["shift",0]}},
      {"patchline":{"source":["quality-select-r",0],"destination":["shift",1]}},
      {"patchline":{"source":["translate",0],"destination":["translate-pak",0]}},
      {"patchline":{"source":["scale",0],"destination":["translate-pak",1]}},
      {"patchline":{"source":["pivot",0],"destination":["translate-pak",2]}},
      {"patchline":{"source":["translate-pak",0],"destination":["pivot-shift",0]}},
      {"patchline":{"source":["pivot-shift",0],"destination":["shift",2]}},
      {"patchline":{"source":["load",0],"destination":["direction-zero",0]}},
      {"patchline":{"source":["direction-zero",0],"destination":["shift",3]}},
      {"patchline":{"source":["shift",0],"destination":["out-l",0]}},
      {"patchline":{"source":["shift",1],"destination":["out-r",0]}}
    ]
  }
}
