{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major":9,"minor":0,"revision":0,"architecture":"x64"},
    "classnamespace":"box",
    "rect":[100.0,100.0,520.0,300.0],
    "boxes":[
      {"box":{"id":"fftin","maxclass":"newobj","text":"fftin~ 1","patching_rect":[40.0,60.0,55.0,22.0]}},
      {"box":{"id":"gizmo","maxclass":"newobj","text":"gizmo~","patching_rect":[150.0,60.0,50.0,22.0]}},
      {"box":{"id":"receive","maxclass":"newobj","text":"r vectorshift-scale","patching_rect":[150.0,20.0,115.0,22.0]}},
      {"box":{"id":"message","maxclass":"message","text":"pitchshift $1","patching_rect":[280.0,20.0,85.0,22.0]}},
      {"box":{"id":"mask-index","maxclass":"newobj","text":"index~ vectorshift-mask","patching_rect":[40.0,105.0,140.0,22.0]}},
      {"box":{"id":"mask-real","maxclass":"newobj","text":"*~","patching_rect":[150.0,105.0,35.0,22.0]}},
      {"box":{"id":"mask-imag","maxclass":"newobj","text":"*~","patching_rect":[205.0,105.0,35.0,22.0]}},
      {"box":{"id":"cartopol","maxclass":"newobj","text":"cartopol~","patching_rect":[150.0,145.0,62.0,22.0]}},
      {"box":{"id":"gate-compare","maxclass":"newobj","text":">~ 0.01","patching_rect":[235.0,145.0,52.0,22.0]}},
      {"box":{"id":"gate-multiply","maxclass":"newobj","text":"*~","patching_rect":[235.0,180.0,35.0,22.0]}},
      {"box":{"id":"gate-threshold","maxclass":"newobj","text":"r vectorshift-gate-threshold","patching_rect":[300.0,105.0,175.0,22.0]}},
      {"box":{"id":"gate-active","maxclass":"newobj","text":"r vectorshift-gate-active","patching_rect":[485.0,105.0,145.0,22.0]}},
      {"box":{"id":"gate-index","maxclass":"newobj","text":"+ 1","patching_rect":[485.0,140.0,35.0,22.0]}},
      {"box":{"id":"gate-select","maxclass":"newobj","text":"selector~ 2","patching_rect":[150.0,215.0,75.0,22.0]}},
      {"box":{"id":"vectral","maxclass":"newobj","text":"vectral~ 1024","patching_rect":[150.0,250.0,85.0,22.0]}},
      {"box":{"id":"freeze-r","maxclass":"newobj","text":"r vectorshift-freeze-slide","patching_rect":[325.0,145.0,160.0,22.0]}},
      {"box":{"id":"freeze-msg","maxclass":"message","text":"slide $1 $1","patching_rect":[325.0,185.0,75.0,22.0]}},
      {"box":{"id":"poltocar","maxclass":"newobj","text":"poltocar~","patching_rect":[150.0,290.0,62.0,22.0]}},
      {"box":{"id":"fftout","maxclass":"newobj","text":"fftout~ 1","patching_rect":[150.0,330.0,62.0,22.0]}}
    ],
    "lines":[
      {"patchline":{"source":["fftin",0],"destination":["gizmo",0]}},
      {"patchline":{"source":["receive",0],"destination":["message",0]}},
      {"patchline":{"source":["message",0],"destination":["gizmo",0]}},
      {"patchline":{"source":["fftin",2],"destination":["mask-index",0]}},
      {"patchline":{"source":["gizmo",0],"destination":["mask-real",0]}},
      {"patchline":{"source":["gizmo",1],"destination":["mask-imag",0]}},
      {"patchline":{"source":["mask-index",0],"destination":["mask-real",1]}},
      {"patchline":{"source":["mask-index",0],"destination":["mask-imag",1]}},
      {"patchline":{"source":["mask-real",0],"destination":["cartopol",0]}},
      {"patchline":{"source":["mask-imag",0],"destination":["cartopol",1]}},
      {"patchline":{"source":["cartopol",0],"destination":["gate-compare",0]}},
      {"patchline":{"source":["cartopol",0],"destination":["gate-multiply",0]}},
      {"patchline":{"source":["gate-compare",0],"destination":["gate-multiply",1]}},
      {"patchline":{"source":["gate-threshold",0],"destination":["gate-compare",1]}},
      {"patchline":{"source":["gate-active",0],"destination":["gate-index",0]}},
      {"patchline":{"source":["gate-index",0],"destination":["gate-select",0]}},
      {"patchline":{"source":["cartopol",0],"destination":["gate-select",1]}},
      {"patchline":{"source":["gate-multiply",0],"destination":["gate-select",2]}},
      {"patchline":{"source":["gate-select",0],"destination":["vectral",0]}},
      {"patchline":{"source":["freeze-r",0],"destination":["freeze-msg",0]}},
      {"patchline":{"source":["freeze-msg",0],"destination":["vectral",0]}},
      {"patchline":{"source":["vectral",0],"destination":["poltocar",0]}},
      {"patchline":{"source":["cartopol",1],"destination":["poltocar",1]}},
      {"patchline":{"source":["poltocar",0],"destination":["fftout",0]}},
      {"patchline":{"source":["poltocar",1],"destination":["fftout",1]}}
    ]
  }
}
