{
  "patcher": {
    "fileversion":1,
    "appversion":{"major":9,"minor":0,"revision":0,"architecture":"x64"},
    "classnamespace":"box",
    "rect":[40.0,40.0,1180.0,720.0],
    "openinpresentation":1,
    "default_fontname":"Ableton Sans Medium",
    "bgcolor":[0.12,0.13,0.135,1.0],
    "boxes":[
      {"box":{"id":"title","maxclass":"comment","text":"VECTORSHIFT","presentation":1,"presentation_rect":[18.0,11.0,120.0,22.0],"textcolor":[0.33,0.87,0.72,1.0]}},
      {"box":{"id":"plugin","maxclass":"newobj","text":"plugin~","patching_rect":[30.0,80.0,50.0,22.0]}},
      {"box":{"id":"plugout","maxclass":"newobj","text":"plugout~","patching_rect":[780.0,610.0,55.0,22.0]}},
      {"box":{"id":"classic","maxclass":"newobj","text":"classic-engine","patching_rect":[150.0,130.0,100.0,22.0]}},
      {"box":{"id":"spectral","maxclass":"newobj","text":"spectral-engine","patching_rect":[150.0,230.0,105.0,22.0]}},

      {"box":{"id":"engine","maxclass":"live.tab","varname":"Engine","parameter_enable":1,"patching_rect":[30.0,30.0,100.0,22.0],"presentation":1,"presentation_rect":[145.0,8.0,150.0,26.0],"numitems":2,"items":["Classic","Spectral"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Engine","parameter_shortname":"Engine","parameter_enum":["Classic","Spectral"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"quality","maxclass":"live.menu","varname":"Quality","parameter_enable":1,"patching_rect":[680.0,30.0,75.0,22.0],"presentation":1,"presentation_rect":[642.0,10.0,76.0,22.0],"items":["Low","Normal","High"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Spectral Quality","parameter_shortname":"Quality","parameter_enum":["Low","Normal","High"],"parameter_type":2,"parameter_initial":[1]}}}},
      {"box":{"id":"engine-expr","maxclass":"newobj","text":"expr cos($f1*1.5707963)","patching_rect":[320.0,55.0,165.0,22.0]}},
      {"box":{"id":"engine-sin","maxclass":"newobj","text":"expr sin($f1*1.5707963)","patching_rect":[500.0,55.0,165.0,22.0]}},
      {"box":{"id":"pack-c","maxclass":"newobj","text":"pack 0. 35","patching_rect":[350.0,95.0,75.0,22.0]}},
      {"box":{"id":"pack-s","maxclass":"newobj","text":"pack 0. 35","patching_rect":[450.0,95.0,75.0,22.0]}},
      {"box":{"id":"line-c","maxclass":"newobj","text":"line~","patching_rect":[350.0,130.0,40.0,22.0]}},
      {"box":{"id":"line-s","maxclass":"newobj","text":"line~","patching_rect":[450.0,130.0,40.0,22.0]}},
      {"box":{"id":"cl-l-gain","maxclass":"newobj","text":"*~","patching_rect":[300.0,180.0,35.0,22.0]}},
      {"box":{"id":"cl-r-gain","maxclass":"newobj","text":"*~","patching_rect":[350.0,180.0,35.0,22.0]}},
      {"box":{"id":"sp-l-gain","maxclass":"newobj","text":"*~","patching_rect":[420.0,230.0,35.0,22.0]}},
      {"box":{"id":"sp-r-gain","maxclass":"newobj","text":"*~","patching_rect":[470.0,230.0,35.0,22.0]}},
      {"box":{"id":"sum-l","maxclass":"newobj","text":"+~","patching_rect":[350.0,280.0,35.0,22.0]}},
      {"box":{"id":"sum-r","maxclass":"newobj","text":"+~","patching_rect":[430.0,280.0,35.0,22.0]}},

      {"box":{"id":"shift","maxclass":"live.dial","varname":"Shift","parameter_enable":1,"patching_rect":[30.0,370.0,48.0,48.0],"presentation":1,"presentation_rect":[18.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Classic Shift","parameter_shortname":"Shift","parameter_mmin":-5000.0,"parameter_mmax":5000.0,"parameter_unitstyle":3,"parameter_initial":[0.0]}}}},
      {"box":{"id":"direction","maxclass":"live.menu","varname":"Direction","parameter_enable":1,"patching_rect":[90.0,370.0,80.0,22.0],"presentation":1,"presentation_rect":[82.0,364.0,92.0,22.0],"items":["Upper","Lower","Stereo Split"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Direction","parameter_shortname":"Direction","parameter_enum":["Upper","Lower","Stereo Split"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"translate","maxclass":"live.dial","varname":"Translate","parameter_enable":1,"patching_rect":[190.0,370.0,48.0,48.0],"presentation":1,"presentation_rect":[184.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Spectral Translate","parameter_shortname":"Translate","parameter_mmin":-10000.0,"parameter_mmax":10000.0,"parameter_unitstyle":3,"parameter_initial":[0.0]}}}},
      {"box":{"id":"scale","maxclass":"live.dial","varname":"Scale","parameter_enable":1,"patching_rect":[250.0,370.0,48.0,48.0],"presentation":1,"presentation_rect":[246.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Frequency Scale","parameter_shortname":"Scale","parameter_mmin":0.25,"parameter_mmax":4.0,"parameter_initial":[1.0]}}}},
      {"box":{"id":"pivot","maxclass":"live.dial","varname":"Pivot","parameter_enable":1,"patching_rect":[310.0,370.0,48.0,48.0],"presentation":1,"presentation_rect":[308.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Scale Pivot","parameter_shortname":"Pivot","parameter_mmin":20.0,"parameter_mmax":10000.0,"parameter_unitstyle":3,"parameter_initial":[1000.0]}}}},

      {"box":{"id":"svf-l","maxclass":"newobj","text":"svf~ 1000. 0.7","patching_rect":[350.0,330.0,95.0,22.0]}},
      {"box":{"id":"svf-r","maxclass":"newobj","text":"svf~ 1000. 0.7","patching_rect":[470.0,330.0,95.0,22.0]}},
      {"box":{"id":"sel-l","maxclass":"newobj","text":"selector~ 5","patching_rect":[350.0,380.0,75.0,22.0]}},
      {"box":{"id":"sel-r","maxclass":"newobj","text":"selector~ 5","patching_rect":[470.0,380.0,75.0,22.0]}},
      {"box":{"id":"filter-mode","maxclass":"live.menu","varname":"FilterMode","parameter_enable":1,"patching_rect":[570.0,330.0,100.0,22.0],"presentation":1,"presentation_rect":[390.0,364.0,112.0,22.0],"items":["Cutoff","Band","Comb","Odd/Even","Gate","Freeze","Random Reject","Harmonic Select"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Filter Mode","parameter_shortname":"Filter","parameter_enum":["Cutoff","Band","Comb","Odd/Even","Gate","Freeze","Random Reject","Harmonic Select"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"filter-index","maxclass":"newobj","text":"expr (($i1==0)*1)+(($i1==1)*3)+(($i1>1)*5)","patching_rect":[570.0,365.0,265.0,22.0]}},
      {"box":{"id":"filter-freq","maxclass":"live.dial","varname":"FilterFrequency","parameter_enable":1,"patching_rect":[690.0,330.0,48.0,48.0],"presentation":1,"presentation_rect":[510.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Filter Frequency","parameter_shortname":"Freq","parameter_mmin":20.0,"parameter_mmax":20000.0,"parameter_unitstyle":3,"parameter_initial":[1000.0]}}}},
      {"box":{"id":"filter-q","maxclass":"live.dial","varname":"FilterQ","parameter_enable":1,"patching_rect":[750.0,330.0,48.0,48.0],"presentation":1,"presentation_rect":[572.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Filter Q","parameter_shortname":"Q","parameter_mmin":0.1,"parameter_mmax":20.0,"parameter_initial":[0.7]}}}},
      {"box":{"id":"filter-amount","maxclass":"live.dial","varname":"FilterAmount","parameter_enable":1,"patching_rect":[810.0,330.0,48.0,48.0],"presentation":1,"presentation_rect":[634.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Filter Amount","parameter_shortname":"Amount","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_unitstyle":1,"parameter_initial":[1.0]}}}},
      {"box":{"id":"mask-buffer","maxclass":"newobj","text":"buffer~ vectorshift-mask 2048","patching_rect":[880.0,330.0,175.0,22.0]}},
      {"box":{"id":"mask-js","maxclass":"newobj","text":"js spectral-mask.js vectorshift-mask","patching_rect":[880.0,365.0,205.0,22.0]}},
      {"box":{"id":"mode-prepend","maxclass":"newobj","text":"prepend mode","patching_rect":[880.0,400.0,90.0,22.0]}},
      {"box":{"id":"freq-prepend","maxclass":"newobj","text":"prepend frequency","patching_rect":[980.0,400.0,110.0,22.0]}},
      {"box":{"id":"q-prepend","maxclass":"newobj","text":"prepend q","patching_rect":[880.0,435.0,75.0,22.0]}},
      {"box":{"id":"amount-prepend","maxclass":"newobj","text":"prepend amount","patching_rect":[965.0,435.0,105.0,22.0]}},
      {"box":{"id":"pivot-prepend","maxclass":"newobj","text":"prepend pivot","patching_rect":[880.0,470.0,90.0,22.0]}},
      {"box":{"id":"freeze-send","maxclass":"newobj","text":"s vectorshift-freeze-slide","patching_rect":[880.0,505.0,160.0,22.0]}},
      {"box":{"id":"gate-active-expr","maxclass":"newobj","text":"== 4","patching_rect":[1050.0,470.0,40.0,22.0]}},
      {"box":{"id":"gate-active-send","maxclass":"newobj","text":"s vectorshift-gate-active","patching_rect":[1050.0,505.0,150.0,22.0]}},
      {"box":{"id":"gate-threshold-expr","maxclass":"newobj","text":"expr pow(10.\\,(-80.+70.*$f1)/20.)","patching_rect":[880.0,540.0,205.0,22.0]}},
      {"box":{"id":"gate-threshold-send","maxclass":"newobj","text":"s vectorshift-gate-threshold","patching_rect":[880.0,575.0,170.0,22.0]}},
      {"box":{"id":"mask-load","maxclass":"newobj","text":"loadbang","patching_rect":[1060.0,330.0,60.0,22.0]}},
      {"box":{"id":"mask-size","maxclass":"message","text":"sizeinsamps 2048","patching_rect":[1060.0,365.0,105.0,22.0]}},
      {"box":{"id":"quality-bins","maxclass":"newobj","text":"expr 512*pow(2.\\,$i1)","patching_rect":[1060.0,400.0,145.0,22.0]}},
      {"box":{"id":"quality-bins-msg","maxclass":"newobj","text":"prepend bins","patching_rect":[1060.0,435.0,85.0,22.0]}},

      {"box":{"id":"mix","maxclass":"live.dial","varname":"DryWet","parameter_enable":1,"patching_rect":[570.0,450.0,48.0,48.0],"presentation":1,"presentation_rect":[700.0,345.0,58.0,58.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Dry Wet","parameter_shortname":"Mix","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_unitstyle":1,"parameter_initial":[1.0]}}}},
      {"box":{"id":"mix-expr","maxclass":"newobj","text":"expr cos($f1*1.5707963)","patching_rect":[570.0,490.0,165.0,22.0]}},
      {"box":{"id":"mix-sin","maxclass":"newobj","text":"expr sin($f1*1.5707963)","patching_rect":[745.0,490.0,165.0,22.0]}},
      {"box":{"id":"dry-pack","maxclass":"newobj","text":"pack 0. 20","patching_rect":[590.0,525.0,75.0,22.0]}},
      {"box":{"id":"wet-pack","maxclass":"newobj","text":"pack 0. 20","patching_rect":[690.0,525.0,75.0,22.0]}},
      {"box":{"id":"dry-line","maxclass":"newobj","text":"line~","patching_rect":[590.0,560.0,42.0,22.0]}},
      {"box":{"id":"wet-line","maxclass":"newobj","text":"line~","patching_rect":[690.0,560.0,42.0,22.0]}},
      {"box":{"id":"wet-l","maxclass":"newobj","text":"*~","patching_rect":[350.0,450.0,35.0,22.0]}},
      {"box":{"id":"wet-r","maxclass":"newobj","text":"*~","patching_rect":[430.0,450.0,35.0,22.0]}},
      {"box":{"id":"dry-l","maxclass":"newobj","text":"*~","patching_rect":[150.0,450.0,35.0,22.0]}},
      {"box":{"id":"dry-r","maxclass":"newobj","text":"*~","patching_rect":[230.0,450.0,35.0,22.0]}},
      {"box":{"id":"dry-delay-l","maxclass":"newobj","text":"delay~ 4096 0","patching_rect":[120.0,415.0,85.0,22.0]}},
      {"box":{"id":"dry-delay-r","maxclass":"newobj","text":"delay~ 4096 0","patching_rect":[215.0,415.0,85.0,22.0]}},
      {"box":{"id":"latency-pak","maxclass":"newobj","text":"pak 0 1","patching_rect":[310.0,415.0,55.0,22.0]}},
      {"box":{"id":"latency-expr","maxclass":"newobj","text":"expr ($i1==1)*256*pow(2.\\,$i2)","patching_rect":[375.0,415.0,195.0,22.0]}},
      {"box":{"id":"mix-l","maxclass":"newobj","text":"+~","patching_rect":[350.0,500.0,35.0,22.0]}},
      {"box":{"id":"mix-r","maxclass":"newobj","text":"+~","patching_rect":[430.0,500.0,35.0,22.0]}},
      {"box":{"id":"limit-l","maxclass":"newobj","text":"tanh~","patching_rect":[350.0,550.0,42.0,22.0]}},
      {"box":{"id":"limit-r","maxclass":"newobj","text":"tanh~","patching_rect":[430.0,550.0,42.0,22.0]}},
      {"box":{"id":"gain","maxclass":"live.gain~","varname":"Output","parameter_enable":1,"patching_rect":[520.0,550.0,110.0,45.0],"presentation":1,"presentation_rect":[764.0,344.0,78.0,55.0]}},

      {"box":{"id":"spectrum","maxclass":"jsui","filename":"vector-spectrum.js","patching_rect":[30.0,430.0,800.0,160.0],"presentation":1,"presentation_rect":[18.0,47.0,824.0,282.0],"border":0}},
      {"box":{"id":"analyzer-in","maxclass":"newobj","text":"jit_fft_viz","patching_rect":[650.0,610.0,70.0,22.0]}},
      {"box":{"id":"analyzer-out","maxclass":"newobj","text":"jit_fft_viz","patching_rect":[730.0,610.0,70.0,22.0]}},
      {"box":{"id":"viz-metro","maxclass":"newobj","text":"qmetro 33","patching_rect":[650.0,645.0,65.0,22.0]}},
      {"box":{"id":"viz-on","maxclass":"live.toggle","varname":"VisualizationOn","parameter_enable":1,"patching_rect":[730.0,645.0,20.0,20.0],"presentation":1,"presentation_rect":[798.0,11.0,20.0,20.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Visualization On","parameter_shortname":"Viz","parameter_mmin":0.0,"parameter_mmax":1.0,"parameter_initial":[1.0]}}}},
      {"box":{"id":"viz-fps","maxclass":"live.menu","varname":"VisualizationFPS","parameter_enable":1,"patching_rect":[760.0,645.0,60.0,22.0],"presentation":1,"presentation_rect":[730.0,10.0,60.0,22.0],"items":["15 FPS","30 FPS","60 FPS"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Visualization FPS","parameter_shortname":"FPS","parameter_enum":["15 FPS","30 FPS","60 FPS"],"parameter_type":2,"parameter_initial":[1]}}}},
      {"box":{"id":"viz-fps-expr","maxclass":"newobj","text":"expr 66.6667/pow(2.\\,$i1)","patching_rect":[830.0,645.0,170.0,22.0]}},
      {"box":{"id":"viz-log","maxclass":"newobj","text":"loadmess 1","patching_rect":[650.0,680.0,70.0,22.0]}},
      {"box":{"id":"modulation-engine","maxclass":"newobj","text":"modulation","patching_rect":[900.0,30.0,75.0,22.0]}},
      {"box":{"id":"mod-source-select","maxclass":"newobj","text":"selector~ 2","patching_rect":[900.0,65.0,75.0,22.0]}},
      {"box":{"id":"mod-source-index","maxclass":"newobj","text":"+ 1","patching_rect":[990.0,65.0,35.0,22.0]}},
      {"box":{"id":"mod-snapshot","maxclass":"newobj","text":"snapshot~ 20","patching_rect":[900.0,100.0,80.0,22.0]}},
      {"box":{"id":"mod-router","maxclass":"newobj","text":"js modulation-router.js","patching_rect":[900.0,135.0,145.0,22.0]}},
      {"box":{"id":"base-shift-msg","maxclass":"newobj","text":"prepend shift","patching_rect":[900.0,170.0,85.0,22.0]}},
      {"box":{"id":"base-translate-msg","maxclass":"newobj","text":"prepend translate","patching_rect":[990.0,170.0,105.0,22.0]}},
      {"box":{"id":"base-scale-msg","maxclass":"newobj","text":"prepend scale","patching_rect":[900.0,205.0,85.0,22.0]}},
      {"box":{"id":"base-pivot-msg","maxclass":"newobj","text":"prepend pivot","patching_rect":[990.0,205.0,85.0,22.0]}},
      {"box":{"id":"base-filter-msg","maxclass":"newobj","text":"prepend filter","patching_rect":[900.0,240.0,85.0,22.0]}},
      {"box":{"id":"mod-value-msg","maxclass":"newobj","text":"prepend modulation","patching_rect":[990.0,240.0,120.0,22.0]}},
      {"box":{"id":"mod-target-msg","maxclass":"newobj","text":"prepend target","patching_rect":[900.0,275.0,90.0,22.0]}},
      {"box":{"id":"mod-depth-msg","maxclass":"newobj","text":"prepend depth","patching_rect":[1000.0,275.0,90.0,22.0]}},
      {"box":{"id":"mod-source","maxclass":"live.tab","varname":"ModSource","parameter_enable":1,"patching_rect":[30.0,620.0,100.0,22.0],"presentation":1,"presentation_rect":[18.0,416.0,106.0,22.0],"numitems":2,"items":["LFO","Envelope"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Mod Source","parameter_shortname":"Source","parameter_enum":["LFO","Envelope"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"mod-shape","maxclass":"live.menu","varname":"LFOShape","parameter_enable":1,"patching_rect":[140.0,620.0,80.0,22.0],"presentation":1,"presentation_rect":[132.0,416.0,78.0,22.0],"items":["Sine","Triangle","Saw","Square","Random"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"LFO Shape","parameter_shortname":"Shape","parameter_enum":["Sine","Triangle","Saw","Square","Random"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"mod-rate","maxclass":"live.dial","varname":"LFORate","parameter_enable":1,"patching_rect":[230.0,610.0,48.0,48.0],"presentation":1,"presentation_rect":[218.0,405.0,48.0,48.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"LFO Rate","parameter_shortname":"Rate","parameter_mmin":0.01,"parameter_mmax":20.0,"parameter_initial":[0.25]}}}},
      {"box":{"id":"mod-target","maxclass":"live.menu","varname":"ModTarget","parameter_enable":1,"patching_rect":[290.0,620.0,90.0,22.0],"presentation":1,"presentation_rect":[274.0,416.0,102.0,22.0],"items":["Shift","Translate","Scale","Pivot","Filter"],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Mod Target","parameter_shortname":"Target","parameter_enum":["Shift","Translate","Scale","Pivot","Filter"],"parameter_type":2,"parameter_initial":[0]}}}},
      {"box":{"id":"mod-depth","maxclass":"live.dial","varname":"ModDepth","parameter_enable":1,"patching_rect":[390.0,610.0,48.0,48.0],"presentation":1,"presentation_rect":[384.0,405.0,48.0,48.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Mod Depth","parameter_shortname":"Depth","parameter_mmin":-1.0,"parameter_mmax":1.0,"parameter_unitstyle":1,"parameter_initial":[0.0]}}}},
      {"box":{"id":"env-attack","maxclass":"live.dial","varname":"EnvAttack","parameter_enable":1,"patching_rect":[450.0,610.0,48.0,48.0],"presentation":1,"presentation_rect":[440.0,405.0,48.0,48.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Envelope Attack","parameter_shortname":"Attack","parameter_mmin":1.0,"parameter_mmax":1000.0,"parameter_unitstyle":2,"parameter_initial":[10.0]}}}},
      {"box":{"id":"env-release","maxclass":"live.dial","varname":"EnvRelease","parameter_enable":1,"patching_rect":[510.0,610.0,48.0,48.0],"presentation":1,"presentation_rect":[496.0,405.0,48.0,48.0],"saved_attribute_attributes":{"valueof":{"parameter_longname":"Envelope Release","parameter_shortname":"Release","parameter_mmin":5.0,"parameter_mmax":3000.0,"parameter_unitstyle":2,"parameter_initial":[250.0]}}}},
      {"box":{"id":"autopattr","maxclass":"newobj","text":"autopattr","patching_rect":[900.0,30.0,60.0,22.0]}},
      {"box":{"id":"pattrstorage","maxclass":"newobj","text":"pattrstorage VectorShift @savemode 3","patching_rect":[900.0,65.0,215.0,22.0]}}
    ],
    "lines":[
      {"patchline":{"source":["plugin",0],"destination":["classic",0]}},{"patchline":{"source":["plugin",1],"destination":["classic",1]}},
      {"patchline":{"source":["plugin",0],"destination":["spectral",0]}},{"patchline":{"source":["plugin",1],"destination":["spectral",1]}},
      {"patchline":{"source":["direction",0],"destination":["classic",3]}},
      {"patchline":{"source":["engine",0],"destination":["engine-expr",0]}},{"patchline":{"source":["engine",0],"destination":["engine-sin",0]}},{"patchline":{"source":["engine-expr",0],"destination":["pack-c",0]}},{"patchline":{"source":["engine-sin",0],"destination":["pack-s",0]}},{"patchline":{"source":["pack-c",0],"destination":["line-c",0]}},{"patchline":{"source":["pack-s",0],"destination":["line-s",0]}},
      {"patchline":{"source":["classic",0],"destination":["cl-l-gain",0]}},{"patchline":{"source":["classic",1],"destination":["cl-r-gain",0]}},{"patchline":{"source":["line-c",0],"destination":["cl-l-gain",1]}},{"patchline":{"source":["line-c",0],"destination":["cl-r-gain",1]}},
      {"patchline":{"source":["spectral",0],"destination":["sp-l-gain",0]}},{"patchline":{"source":["spectral",1],"destination":["sp-r-gain",0]}},{"patchline":{"source":["line-s",0],"destination":["sp-l-gain",1]}},{"patchline":{"source":["line-s",0],"destination":["sp-r-gain",1]}},
      {"patchline":{"source":["cl-l-gain",0],"destination":["sum-l",0]}},{"patchline":{"source":["sp-l-gain",0],"destination":["sum-l",1]}},{"patchline":{"source":["cl-r-gain",0],"destination":["sum-r",0]}},{"patchline":{"source":["sp-r-gain",0],"destination":["sum-r",1]}},
      {"patchline":{"source":["sum-l",0],"destination":["svf-l",0]}},{"patchline":{"source":["sum-r",0],"destination":["svf-r",0]}},{"patchline":{"source":["filter-q",0],"destination":["svf-l",2]}},{"patchline":{"source":["filter-q",0],"destination":["svf-r",2]}},
      {"patchline":{"source":["filter-mode",0],"destination":["filter-index",0]}},{"patchline":{"source":["filter-index",0],"destination":["sel-l",0]}},{"patchline":{"source":["filter-index",0],"destination":["sel-r",0]}},
      {"patchline":{"source":["filter-mode",0],"destination":["mode-prepend",0]}},{"patchline":{"source":["mode-prepend",0],"destination":["mask-js",0]}},
      {"patchline":{"source":["filter-mode",0],"destination":["gate-active-expr",0]}},{"patchline":{"source":["gate-active-expr",0],"destination":["gate-active-send",0]}},
      {"patchline":{"source":["filter-q",0],"destination":["q-prepend",0]}},{"patchline":{"source":["q-prepend",0],"destination":["mask-js",0]}},
      {"patchline":{"source":["filter-amount",0],"destination":["amount-prepend",0]}},{"patchline":{"source":["amount-prepend",0],"destination":["mask-js",0]}},
      {"patchline":{"source":["filter-amount",0],"destination":["gate-threshold-expr",0]}},{"patchline":{"source":["gate-threshold-expr",0],"destination":["gate-threshold-send",0]}},
      {"patchline":{"source":["plugin",0],"destination":["modulation-engine",0]}},{"patchline":{"source":["mod-rate",0],"destination":["modulation-engine",1]}},{"patchline":{"source":["mod-shape",0],"destination":["modulation-engine",2]}},{"patchline":{"source":["env-attack",0],"destination":["modulation-engine",3]}},{"patchline":{"source":["env-release",0],"destination":["modulation-engine",4]}},
      {"patchline":{"source":["modulation-engine",0],"destination":["mod-source-select",1]}},{"patchline":{"source":["modulation-engine",1],"destination":["mod-source-select",2]}},{"patchline":{"source":["mod-source",0],"destination":["mod-source-index",0]}},{"patchline":{"source":["mod-source-index",0],"destination":["mod-source-select",0]}},{"patchline":{"source":["mod-source-select",0],"destination":["mod-snapshot",0]}},{"patchline":{"source":["mod-snapshot",0],"destination":["mod-value-msg",0]}},{"patchline":{"source":["mod-value-msg",0],"destination":["mod-router",0]}},
      {"patchline":{"source":["shift",0],"destination":["base-shift-msg",0]}},{"patchline":{"source":["base-shift-msg",0],"destination":["mod-router",0]}},{"patchline":{"source":["translate",0],"destination":["base-translate-msg",0]}},{"patchline":{"source":["base-translate-msg",0],"destination":["mod-router",0]}},{"patchline":{"source":["scale",0],"destination":["base-scale-msg",0]}},{"patchline":{"source":["base-scale-msg",0],"destination":["mod-router",0]}},{"patchline":{"source":["pivot",0],"destination":["base-pivot-msg",0]}},{"patchline":{"source":["base-pivot-msg",0],"destination":["mod-router",0]}},{"patchline":{"source":["filter-freq",0],"destination":["base-filter-msg",0]}},{"patchline":{"source":["base-filter-msg",0],"destination":["mod-router",0]}},
      {"patchline":{"source":["mod-target",0],"destination":["mod-target-msg",0]}},{"patchline":{"source":["mod-target-msg",0],"destination":["mod-router",0]}},{"patchline":{"source":["mod-depth",0],"destination":["mod-depth-msg",0]}},{"patchline":{"source":["mod-depth-msg",0],"destination":["mod-router",0]}},
      {"patchline":{"source":["mod-router",0],"destination":["classic",2]}},{"patchline":{"source":["mod-router",1],"destination":["spectral",2]}},{"patchline":{"source":["mod-router",2],"destination":["spectral",3]}},{"patchline":{"source":["mod-router",3],"destination":["spectral",4]}},{"patchline":{"source":["quality",0],"destination":["spectral",5]}},{"patchline":{"source":["mod-router",3],"destination":["pivot-prepend",0]}},{"patchline":{"source":["pivot-prepend",0],"destination":["mask-js",0]}},{"patchline":{"source":["mod-router",4],"destination":["svf-l",1]}},{"patchline":{"source":["mod-router",4],"destination":["svf-r",1]}},{"patchline":{"source":["mod-router",4],"destination":["freq-prepend",0]}},{"patchline":{"source":["freq-prepend",0],"destination":["mask-js",0]}},
      {"patchline":{"source":["mask-load",0],"destination":["mask-js",0]}},{"patchline":{"source":["mask-load",0],"destination":["mask-size",0]}},{"patchline":{"source":["mask-size",0],"destination":["mask-buffer",0]}},{"patchline":{"source":["mask-js",0],"destination":["freeze-send",0]}},
      {"patchline":{"source":["quality",0],"destination":["quality-bins",0]}},{"patchline":{"source":["quality-bins",0],"destination":["quality-bins-msg",0]}},{"patchline":{"source":["quality-bins-msg",0],"destination":["mask-js",0]}},
      {"patchline":{"source":["svf-l",0],"destination":["sel-l",1]}},{"patchline":{"source":["svf-l",1],"destination":["sel-l",2]}},{"patchline":{"source":["svf-l",2],"destination":["sel-l",3]}},{"patchline":{"source":["svf-l",3],"destination":["sel-l",4]}},
      {"patchline":{"source":["svf-r",0],"destination":["sel-r",1]}},{"patchline":{"source":["svf-r",1],"destination":["sel-r",2]}},{"patchline":{"source":["svf-r",2],"destination":["sel-r",3]}},{"patchline":{"source":["svf-r",3],"destination":["sel-r",4]}},
      {"patchline":{"source":["sum-l",0],"destination":["sel-l",5]}},{"patchline":{"source":["sum-r",0],"destination":["sel-r",5]}},
      {"patchline":{"source":["mix",0],"destination":["mix-expr",0]}},{"patchline":{"source":["mix",0],"destination":["mix-sin",0]}},{"patchline":{"source":["mix-expr",0],"destination":["dry-pack",0]}},{"patchline":{"source":["mix-sin",0],"destination":["wet-pack",0]}},{"patchline":{"source":["dry-pack",0],"destination":["dry-line",0]}},{"patchline":{"source":["wet-pack",0],"destination":["wet-line",0]}},
      {"patchline":{"source":["sel-l",0],"destination":["wet-l",0]}},{"patchline":{"source":["sel-r",0],"destination":["wet-r",0]}},{"patchline":{"source":["wet-line",0],"destination":["wet-l",1]}},{"patchline":{"source":["wet-line",0],"destination":["wet-r",1]}},
      {"patchline":{"source":["plugin",0],"destination":["dry-delay-l",0]}},{"patchline":{"source":["plugin",1],"destination":["dry-delay-r",0]}},{"patchline":{"source":["dry-delay-l",0],"destination":["dry-l",0]}},{"patchline":{"source":["dry-delay-r",0],"destination":["dry-r",0]}},{"patchline":{"source":["engine",0],"destination":["latency-pak",0]}},{"patchline":{"source":["quality",0],"destination":["latency-pak",1]}},{"patchline":{"source":["latency-pak",0],"destination":["latency-expr",0]}},{"patchline":{"source":["latency-expr",0],"destination":["dry-delay-l",1]}},{"patchline":{"source":["latency-expr",0],"destination":["dry-delay-r",1]}},{"patchline":{"source":["dry-line",0],"destination":["dry-l",1]}},{"patchline":{"source":["dry-line",0],"destination":["dry-r",1]}},
      {"patchline":{"source":["wet-l",0],"destination":["mix-l",0]}},{"patchline":{"source":["dry-l",0],"destination":["mix-l",1]}},{"patchline":{"source":["wet-r",0],"destination":["mix-r",0]}},{"patchline":{"source":["dry-r",0],"destination":["mix-r",1]}},
      {"patchline":{"source":["mix-l",0],"destination":["limit-l",0]}},{"patchline":{"source":["mix-r",0],"destination":["limit-r",0]}},{"patchline":{"source":["limit-l",0],"destination":["gain",0]}},{"patchline":{"source":["limit-r",0],"destination":["gain",1]}},{"patchline":{"source":["gain",0],"destination":["plugout",0]}},{"patchline":{"source":["gain",1],"destination":["plugout",1]}}
      ,{"patchline":{"source":["viz-on",0],"destination":["viz-metro",0]}},{"patchline":{"source":["viz-fps",0],"destination":["viz-fps-expr",0]}},{"patchline":{"source":["viz-fps-expr",0],"destination":["viz-metro",1]}},
      {"patchline":{"source":["viz-metro",0],"destination":["analyzer-in",0]}},{"patchline":{"source":["viz-metro",0],"destination":["analyzer-out",0]}},{"patchline":{"source":["plugin",0],"destination":["analyzer-in",1]}},{"patchline":{"source":["gain",0],"destination":["analyzer-out",1]}},
      {"patchline":{"source":["viz-log",0],"destination":["analyzer-in",2]}},{"patchline":{"source":["viz-log",0],"destination":["analyzer-out",2]}},{"patchline":{"source":["analyzer-in",1],"destination":["spectrum",0]}},{"patchline":{"source":["analyzer-out",1],"destination":["spectrum",1]}}
    ],
    "dependency_cache":[
      {"name":"classic-engine.maxpat","bootpath":".","patcherrelativepath":".","type":"JSON","implicit":1},
      {"name":"spectral-engine.maxpat","bootpath":".","patcherrelativepath":".","type":"JSON","implicit":1},
      {"name":"spectral-core.maxpat","bootpath":".","patcherrelativepath":".","type":"JSON","implicit":1},
      {"name":"modulation.maxpat","bootpath":".","patcherrelativepath":".","type":"JSON","implicit":1},
      {"name":"vector-spectrum.js","bootpath":"../code","patcherrelativepath":"../code","type":"TEXT","implicit":1}
    ]
  }
}
